# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changePass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import MySQLdb as mdb


class Ui_ChangePasswordWindow(object):
    id = 0
    
    def closeWindows(self):
        current_window = QtWidgets.QApplication.activeWindow()
        if current_window is not None:
            current_window.close()
            
    def receiveId(get_id):
        Ui_ChangePasswordWindow.id = get_id
        
    def verifyAcc(self):
        old_password = self.old_psw.text()
        db = mdb.connect('localhost','root','','music_app')
        db_password = db.cursor()
        db_password.execute("SELECT password FROM user_management WHERE user_id = '"+str(Ui_ChangePasswordWindow.id)+"'")
        get_password = db_password.fetchone()[0]
        
        if old_password == get_password:
            QMessageBox.information(None, "Verify successful!", "Please enter your new password!")
            self.widget_2.setEnabled(True)
            self.widget.setEnabled(False)
        else:
            QMessageBox.critical(None, "Verify fail!", "Your password is incorrect!")
    
    def changePsw(self):
        new_password = self.new_psw.text()
        confirm_password = self.confirm_psw.text()
        
        if len(new_password) > 16 or len(new_password) < 8:
            QMessageBox.critical(None, "Change password fail!", "Password must be between 8 and 16 characters!")
        elif new_password != confirm_password:
            QMessageBox.critical(None, "Change password fail!", "Password does not match!")
        else:
            try:
                db = mdb.connect('localhost', 'root', '', 'music_app')
                query = db.cursor()
                
                update_password = "UPDATE `user_management` SET `password`=%s WHERE `user_id`=%s"
                query.execute(update_password, (new_password, str(Ui_ChangePasswordWindow.id)))
                
                db.commit()
                db.close()
                
                QMessageBox.information(None, "Change password successful!", "Your password has been changed!")
                self.closeWindows()
                
            except mdb.Error as e:
                print(f"Error: {e}")
                QMessageBox.critical(None, "Database Error", f"Error: {e}")      
                    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"font: 10pt \"Arial Rounded MT Bold\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("font: 20pt \"Arial Rounded MT Bold\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.old_psw = QtWidgets.QLineEdit(self.widget)
        self.old_psw.setObjectName("old_psw")
        self.horizontalLayout.addWidget(self.old_psw, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verify = QtWidgets.QPushButton(self.widget)
        self.verify.setObjectName("verify")
        self.verticalLayout_2.addWidget(self.verify)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.new_psw = QtWidgets.QLineEdit(self.widget_2)
        self.new_psw.setObjectName("new_psw")
        self.horizontalLayout_2.addWidget(self.new_psw, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.confirm_psw = QtWidgets.QLineEdit(self.widget_2)
        self.confirm_psw.setObjectName("confirm_psw")
        self.horizontalLayout_3.addWidget(self.confirm_psw, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.submit = QtWidgets.QPushButton(self.widget_2)
        self.submit.setObjectName("submit")
        self.horizontalLayout_4.addWidget(self.submit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Change Password"))
        self.label.setText(_translate("MainWindow", "Old password:"))
        self.verify.setText(_translate("MainWindow", "Verify account"))
        self.label_2.setText(_translate("MainWindow", "New password:"))
        self.label_3.setText(_translate("MainWindow", "Confirm password:"))
        self.pushButton.setText(_translate("MainWindow", "Cancel"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        
        self.widget_2.setEnabled(False)
        self.verify.clicked.connect(self.verifyAcc)
        self.submit.clicked.connect(self.changePsw)
        self.pushButton.clicked.connect(self.closeWindows)
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ChangePasswordWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
